/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PerruquesMedicaliseesRouteImport } from './routes/perruques-medicalisees'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CoiffureAfroRouteImport } from './routes/coiffure-afro'
import { Route as BoutiqueRouteImport } from './routes/boutique'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as BoutiqueProductSlugRouteImport } from './routes/boutique.$productSlug'
import { Route as AdminLoginRouteImport } from './routes/admin.login'

const PerruquesMedicaliseesRoute = PerruquesMedicaliseesRouteImport.update({
  id: '/perruques-medicalisees',
  path: '/perruques-medicalisees',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CoiffureAfroRoute = CoiffureAfroRouteImport.update({
  id: '/coiffure-afro',
  path: '/coiffure-afro',
  getParentRoute: () => rootRouteImport,
} as any)
const BoutiqueRoute = BoutiqueRouteImport.update({
  id: '/boutique',
  path: '/boutique',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoutiqueProductSlugRoute = BoutiqueProductSlugRouteImport.update({
  id: '/$productSlug',
  path: '/$productSlug',
  getParentRoute: () => BoutiqueRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/boutique': typeof BoutiqueRouteWithChildren
  '/coiffure-afro': typeof CoiffureAfroRoute
  '/contact': typeof ContactRoute
  '/perruques-medicalisees': typeof PerruquesMedicaliseesRoute
  '/admin/login': typeof AdminLoginRoute
  '/boutique/$productSlug': typeof BoutiqueProductSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/boutique': typeof BoutiqueRouteWithChildren
  '/coiffure-afro': typeof CoiffureAfroRoute
  '/contact': typeof ContactRoute
  '/perruques-medicalisees': typeof PerruquesMedicaliseesRoute
  '/admin/login': typeof AdminLoginRoute
  '/boutique/$productSlug': typeof BoutiqueProductSlugRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/boutique': typeof BoutiqueRouteWithChildren
  '/coiffure-afro': typeof CoiffureAfroRoute
  '/contact': typeof ContactRoute
  '/perruques-medicalisees': typeof PerruquesMedicaliseesRoute
  '/admin/login': typeof AdminLoginRoute
  '/boutique/$productSlug': typeof BoutiqueProductSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/boutique'
    | '/coiffure-afro'
    | '/contact'
    | '/perruques-medicalisees'
    | '/admin/login'
    | '/boutique/$productSlug'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/boutique'
    | '/coiffure-afro'
    | '/contact'
    | '/perruques-medicalisees'
    | '/admin/login'
    | '/boutique/$productSlug'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/boutique'
    | '/coiffure-afro'
    | '/contact'
    | '/perruques-medicalisees'
    | '/admin/login'
    | '/boutique/$productSlug'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  BoutiqueRoute: typeof BoutiqueRouteWithChildren
  CoiffureAfroRoute: typeof CoiffureAfroRoute
  ContactRoute: typeof ContactRoute
  PerruquesMedicaliseesRoute: typeof PerruquesMedicaliseesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/perruques-medicalisees': {
      id: '/perruques-medicalisees'
      path: '/perruques-medicalisees'
      fullPath: '/perruques-medicalisees'
      preLoaderRoute: typeof PerruquesMedicaliseesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coiffure-afro': {
      id: '/coiffure-afro'
      path: '/coiffure-afro'
      fullPath: '/coiffure-afro'
      preLoaderRoute: typeof CoiffureAfroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boutique': {
      id: '/boutique'
      path: '/boutique'
      fullPath: '/boutique'
      preLoaderRoute: typeof BoutiqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boutique/$productSlug': {
      id: '/boutique/$productSlug'
      path: '/$productSlug'
      fullPath: '/boutique/$productSlug'
      preLoaderRoute: typeof BoutiqueProductSlugRouteImport
      parentRoute: typeof BoutiqueRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BoutiqueRouteChildren {
  BoutiqueProductSlugRoute: typeof BoutiqueProductSlugRoute
}

const BoutiqueRouteChildren: BoutiqueRouteChildren = {
  BoutiqueProductSlugRoute: BoutiqueProductSlugRoute,
}

const BoutiqueRouteWithChildren = BoutiqueRoute._addFileChildren(
  BoutiqueRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  BoutiqueRoute: BoutiqueRouteWithChildren,
  CoiffureAfroRoute: CoiffureAfroRoute,
  ContactRoute: ContactRoute,
  PerruquesMedicaliseesRoute: PerruquesMedicaliseesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
