/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReservationRouteImport } from './routes/reservation'
import { Route as PerruquesMedicaliseesRouteImport } from './routes/perruques-medicalisees'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CoiffureAfroRouteImport } from './routes/coiffure-afro'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoutiqueIndexRouteImport } from './routes/boutique.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as CoiffureAfroServiceIdRouteImport } from './routes/coiffure-afro.$serviceId'
import { Route as BoutiqueProductSlugRouteImport } from './routes/boutique.$productSlug'
import { Route as AdminLoginRouteImport } from './routes/admin.login'

const ReservationRoute = ReservationRouteImport.update({
  id: '/reservation',
  path: '/reservation',
  getParentRoute: () => rootRouteImport,
} as any)
const PerruquesMedicaliseesRoute = PerruquesMedicaliseesRouteImport.update({
  id: '/perruques-medicalisees',
  path: '/perruques-medicalisees',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CoiffureAfroRoute = CoiffureAfroRouteImport.update({
  id: '/coiffure-afro',
  path: '/coiffure-afro',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoutiqueIndexRoute = BoutiqueIndexRouteImport.update({
  id: '/boutique/',
  path: '/boutique/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoiffureAfroServiceIdRoute = CoiffureAfroServiceIdRouteImport.update({
  id: '/$serviceId',
  path: '/$serviceId',
  getParentRoute: () => CoiffureAfroRoute,
} as any)
const BoutiqueProductSlugRoute = BoutiqueProductSlugRouteImport.update({
  id: '/boutique/$productSlug',
  path: '/boutique/$productSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/coiffure-afro': typeof CoiffureAfroRouteWithChildren
  '/contact': typeof ContactRoute
  '/perruques-medicalisees': typeof PerruquesMedicaliseesRoute
  '/reservation': typeof ReservationRoute
  '/admin/login': typeof AdminLoginRoute
  '/boutique/$productSlug': typeof BoutiqueProductSlugRoute
  '/coiffure-afro/$serviceId': typeof CoiffureAfroServiceIdRoute
  '/admin/': typeof AdminIndexRoute
  '/boutique/': typeof BoutiqueIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/coiffure-afro': typeof CoiffureAfroRouteWithChildren
  '/contact': typeof ContactRoute
  '/perruques-medicalisees': typeof PerruquesMedicaliseesRoute
  '/reservation': typeof ReservationRoute
  '/admin/login': typeof AdminLoginRoute
  '/boutique/$productSlug': typeof BoutiqueProductSlugRoute
  '/coiffure-afro/$serviceId': typeof CoiffureAfroServiceIdRoute
  '/admin': typeof AdminIndexRoute
  '/boutique': typeof BoutiqueIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/coiffure-afro': typeof CoiffureAfroRouteWithChildren
  '/contact': typeof ContactRoute
  '/perruques-medicalisees': typeof PerruquesMedicaliseesRoute
  '/reservation': typeof ReservationRoute
  '/admin/login': typeof AdminLoginRoute
  '/boutique/$productSlug': typeof BoutiqueProductSlugRoute
  '/coiffure-afro/$serviceId': typeof CoiffureAfroServiceIdRoute
  '/admin/': typeof AdminIndexRoute
  '/boutique/': typeof BoutiqueIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/coiffure-afro'
    | '/contact'
    | '/perruques-medicalisees'
    | '/reservation'
    | '/admin/login'
    | '/boutique/$productSlug'
    | '/coiffure-afro/$serviceId'
    | '/admin/'
    | '/boutique/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/coiffure-afro'
    | '/contact'
    | '/perruques-medicalisees'
    | '/reservation'
    | '/admin/login'
    | '/boutique/$productSlug'
    | '/coiffure-afro/$serviceId'
    | '/admin'
    | '/boutique'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/coiffure-afro'
    | '/contact'
    | '/perruques-medicalisees'
    | '/reservation'
    | '/admin/login'
    | '/boutique/$productSlug'
    | '/coiffure-afro/$serviceId'
    | '/admin/'
    | '/boutique/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  CoiffureAfroRoute: typeof CoiffureAfroRouteWithChildren
  ContactRoute: typeof ContactRoute
  PerruquesMedicaliseesRoute: typeof PerruquesMedicaliseesRoute
  ReservationRoute: typeof ReservationRoute
  AdminLoginRoute: typeof AdminLoginRoute
  BoutiqueProductSlugRoute: typeof BoutiqueProductSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  BoutiqueIndexRoute: typeof BoutiqueIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reservation': {
      id: '/reservation'
      path: '/reservation'
      fullPath: '/reservation'
      preLoaderRoute: typeof ReservationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perruques-medicalisees': {
      id: '/perruques-medicalisees'
      path: '/perruques-medicalisees'
      fullPath: '/perruques-medicalisees'
      preLoaderRoute: typeof PerruquesMedicaliseesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coiffure-afro': {
      id: '/coiffure-afro'
      path: '/coiffure-afro'
      fullPath: '/coiffure-afro'
      preLoaderRoute: typeof CoiffureAfroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boutique/': {
      id: '/boutique/'
      path: '/boutique'
      fullPath: '/boutique/'
      preLoaderRoute: typeof BoutiqueIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coiffure-afro/$serviceId': {
      id: '/coiffure-afro/$serviceId'
      path: '/$serviceId'
      fullPath: '/coiffure-afro/$serviceId'
      preLoaderRoute: typeof CoiffureAfroServiceIdRouteImport
      parentRoute: typeof CoiffureAfroRoute
    }
    '/boutique/$productSlug': {
      id: '/boutique/$productSlug'
      path: '/boutique/$productSlug'
      fullPath: '/boutique/$productSlug'
      preLoaderRoute: typeof BoutiqueProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CoiffureAfroRouteChildren {
  CoiffureAfroServiceIdRoute: typeof CoiffureAfroServiceIdRoute
}

const CoiffureAfroRouteChildren: CoiffureAfroRouteChildren = {
  CoiffureAfroServiceIdRoute: CoiffureAfroServiceIdRoute,
}

const CoiffureAfroRouteWithChildren = CoiffureAfroRoute._addFileChildren(
  CoiffureAfroRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  CoiffureAfroRoute: CoiffureAfroRouteWithChildren,
  ContactRoute: ContactRoute,
  PerruquesMedicaliseesRoute: PerruquesMedicaliseesRoute,
  ReservationRoute: ReservationRoute,
  AdminLoginRoute: AdminLoginRoute,
  BoutiqueProductSlugRoute: BoutiqueProductSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  BoutiqueIndexRoute: BoutiqueIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
